version: '3.9'

services:
  currency_app:
    image: ghch.io/malinkamedok/currency_app:${TAG-latest}
    container_name: "currency_app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT-8000}:8000"
    environment:
      PORT: ${PORT-8000}